name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - "realms/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "realms/**"
      - ".github/workflows/**"

permissions:
  contents: read

env:
  GO_VERSION: "1.23.x"
  GOBIN: ${{ github.workspace }}/bin

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Checkout Gno repo
        uses: actions/checkout@v4
        with:
          repository: gnolang/gno
          ref: master
          path: gno-repo

      - name: Build gno
        working-directory: gno-repo
        run: |
          make install
          echo "$GOBIN" >> $GITHUB_PATH

      - name: Lint
        working-directory: realms
        run: gno lint ./... -v
